<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'About' => 'Über uns',
    'Add' => 'Hinzufügen',
    'Add airplane' => 'Flugzeug hinzufügen',
    'Airplane is parked at' => 'Das Flugzeug befindet sich am',
    'Airplanes' => 'Flugzeuge',
    'Airplanes for rent' => 'Flugzeuge zu mieten',
    'Airport' => 'Flugplatz',
    'Back' => 'Zurück',
    'Back to airport' => 'Zurück zum Flugplatz',
    'Back to map' => 'Zurück zur Karte',
    'Create account' => 'Konto erstellen',
    'Create new account' => 'Neues Konto erstellen',
    'Description' => 'Beschreibung',
    'Details about airplane' => 'Details zum Flugzeug',
    'Email' => 'E-mail',
    'Forgot your password?' => 'Passwort vergessen?',
    'Free' => 'Gratis',
    'Login' => 'Einloggen',
    'Map' => 'Karte',
    'More info' => 'Mehr Info',
    'Name' => 'Name',
    'No account?' => 'Kein Konto?',
    'Note' => 'Notiz',
    'Organisation' => 'Verein',
    'Password' => 'Kennwort',
    'Price' => 'Preis',
    'Price per hour' => 'Stundenpreis',
    'Price with discount' => 'Preis mit Rabatt',
    'Registration' => 'Immatrikulation',
    'Remember me' => 'Angemeldet bleiben',
    'Rent your perfect and affordable airplane!' => 'Mieten Sie Ihr perfektes und erschwingliches Flugzeug!',
    'Seats' => 'Sitzplätze',
    'Seats no' => 'Sitze',
    'Success' => 'Erfolg',
    'Tail number' => 'Kenn-zeichen',
    'To rent this plane, please contact' => 'Um dieses Flugzeug zu mieten, wenden Sie sich bitte an',
    'Update' => 'Aktualisieren',
    'Update organisation' => 'Verein bearbeiten',
    'With VAT' => 'mit 7.7% MwSt',
    'or' => 'oder',
    'per hour' => 'pro Stunde',
    'Account' => '',
    'Add organisation' => '',
    'Add your own airplane' => '',
    'All information without guarantee. Actual price may vary. Please concact organisation for details' => '',
    'Any extra details about the plane or rental conditions' => '',
    'Change password' => '',
    'Code' => '',
    'Full name and contact details' => '',
    'Image URL' => '',
    'Invalid price' => '',
    'Link to image. Please use external services to store an image.' => '',
    'Link where users can find more details about the airplane' => '',
    'My airplanes' => '',
    'New password' => '',
    'New password saved' => '',
    'Not actual image' => '',
    'Old password' => '',
    'Password reset' => '',
    'Please check your inbox for verification email.' => '',
    'Registration is disabled' => '',
    'Reset' => '',
    'Reset password' => '',
    'Select airport' => '',
    'Thank you for registration' => '',
    'The lowest price with membership discount or package discount' => '',
    'Update airplane' => '',
    'Web page' => '',
    'Website' => '',
    'Welcome' => '',
    'Wikipedia URL' => '',
    'Your email has been confirmed!' => '',
    'Cancel' => 'Abbrechen',
    'Register' => 'Konto erstellen',
    'Save' => 'Speichern',
];
