<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'About' => 'O nas',
    'Account' => 'Račun',
    'Add' => 'Dodaj',
    'Add airplane' => 'Dodaj letalo',
    'Add organisation' => 'Dodaj društvo',
    'Add your own airplane' => 'Dodaj lastno letalo',
    'Airplane is parked at' => 'Letalo je parkirano na',
    'Airplanes' => 'Letala',
    'Airplanes for rent' => 'Letala za najem',
    'Airport' => 'Letališče',
    'All information without guarantee. Actual price may vary. Please concact organisation for details' => 'Vse informacije brez garancije. Dejanske cene lahko odstopajo. Prosimo kontaktirajte društvo za podrobnosti',
    'Any extra details about the plane or rental conditions' => 'Dodatne podrobnosti o letalu ali pogoji najema',
    'Back' => 'Nazaj',
    'Back to airport' => 'Nazaj na letališče',
    'Back to map' => 'Nazaj na zemljevid',
    'Change password' => 'Spremeni geslo',
    'Code' => 'Šifra',
    'Contact' => 'Kontakt',
    'Create account' => 'Odpri račun',
    'Create new account' => 'Ustvarite nov račun',
    'Description' => 'Opis',
    'Details about airplane' => 'Podrobnosti o letalu',
    'Drop us an email at' => 'Pošljite nam sporočilo na',
    'Email' => 'Email',
    'Forgot your password?' => 'Pozabljeno geslo?',
    'Free' => 'Brezplačno',
    'Full name and contact details' => 'Polni naziv in kontaktni podatki',
    'Image URL' => 'URL slike',
    'Info' => 'Info',
    'Invalid price' => 'Neveljavna cena',
    'Link to image. Please use external services to store an image.' => 'Povezava do slike. Prosimo uporabite zunanje storitve za shrambo slike',
    'Link where users can find more details about the airplane' => 'Povezava, kjer lahko uporabniki najdejo več informacij o letalu',
    'Login' => 'Prijava',
    'Map' => 'Zemljevid',
    'More info' => 'Več informacij',
    'My airplanes' => 'Moja letala',
    'Name' => 'Naziv',
    'New password' => 'Novo geslo',
    'New password saved' => 'Novo geslo je shranjeno',
    'No account?' => 'Brez računa?',
    'Not actual image' => 'Slika je simbolična',
    'Note' => 'Opomba',
    'Old password' => 'Staro geslo',
    'Organisation' => 'Društvo',
    'Our service is to provide you the details where you can rent an airplane.' => 'Naša storitev je podati informacije, kje lahko najamete letalo.',
    'Password' => 'Geslo',
    'Password reset' => 'Ponastavi geslo',
    'Please check your inbox for verification email.' => 'Prosimo preverite vaš poštni predal za verifikacijo',
    'Price' => 'Cena',
    'Price per hour' => 'Cena na uro',
    'Price with discount' => 'Cena z popustom',
    'Registration' => 'Registracija',
    'Registration is disabled' => 'Registracija je onemogočena',
    'Remember me' => 'Zapomni si me',
    'Rent your perfect and affordable airplane!' => 'Najemite vaše popolno in cenovno dostopno letalo!',
    'Reset' => 'Ponastavi',
    'Reset password' => 'Ponastavi geslo',
    'Seats' => 'Število sedežev',
    'Seats no' => 'Število sedežev',
    'Select airport' => 'Izberi letališče',
    'Success' => 'Uspešno',
    'Tail number' => 'Registracijska številka',
    'Thank you for registration' => 'Hvala za registracijo',
    'The lowest price with membership discount or package discount' => 'Najnižja cena z članskim ali paketnim popustom',
    'To rent this plane, please contact' => 'Za najem letala prosimo kontaktirajte',
    'Update' => 'Posodobi',
    'Update airplane' => 'Posodobi letalo',
    'Update organisation' => 'Posodobi društvo',
    'We do not own any of the airplanes. 
        We do not process rentals.
        Prices are not binding to anyone. 
        All information is without guarantee. ' => 'Letala niso v naši lasti. Ne procesiramo najemov. Cene niso obvezujoče za nikogar. Vse informacije brez garancije.',
    'Web page' => 'Spletna stran',
    'Website' => 'Splenta stran',
    'Welcome' => 'Pozdravljeni',
    'Welcome to AirRenty!' => 'Pozdravljeni na AirRenty!',
    'Wikipedia URL' => 'Wikipedia URL',
    'With VAT' => 'z 22% DDV',
    'Your email has been confirmed!' => 'Vaš email je potrjen!',
    'or' => 'ali',
    'per hour' => 'na uro',
    'All services are provided without warranty of any kind, 
        either express or implied. We do not represent that this Site will be 
        available 100% of the time to meet your needs. We will strive to provide 
        you with the Service as soon as possible but there are no guarantees that 
        access will not be interrupted, or that there will be no delays, 
        failures, errors, omissions or loss of transmitted information.
        
        We will use reasonable endeavours to ensure that the Site can normally be accessed by you 
        in accordance with these Terms of Use. We may suspend use of the Site for maintenance 
        and will make reasonable efforts to give you notice. 
        You acknowledge that this may not be possible in an emergency.
        ' => 'Vse storitve so podane brez kakršnekoli garancije, bodisi izrecno ali implicitno. 
          Ne zagotavljamo, da bo to spletno mesto na voljo 100% časa za izpolnitev vaših potreb.
          Prizadevali si bomo, da bomo zagotavljali storitev, vendar brez garancije da bo dostop nemoten ali
          da ne bo prihajalo do zakasnitev, napak, opustitve ali izgube poslanih informacij.
          Uporabili bomo razumna prizadevanja za zagotovitev, da lahko do spletnega mesta dostopate
          v skladu s temi pogoji uporabe. Za vzdrževanje lahko spletno mesto prekinemo brez predhodne najave.
    ',
    'EXCEPT IN JURISDICTIONS WHERE SUCH PROVISIONS ARE RESTRICTED, IN NO EVENT WILL COMPANY OR ITS DIRECTORS, 
          EMPLOYEES OR AGENTS BE LIABLE TO YOU OR ANY THIRD PERSON FOR ANY INDIRECT, CONSEQUENTIAL, 
          EXEMPLARY, INCIDENTAL, SPECIAL OR PUNITIVE DAMAGES, INCLUDING FOR ANY LOST PROFITS OR LOST DATA 
          ARISING FROM YOUR USE OF THE SITE OR THE SERVICE OR ANY OF THE SITE CONTENT OR OTHER MATERIALS 
          ON OR ACCESSED THROUGH THE SITE, EVEN IF THE COMPANY IS AWARE OR HAS BEEN ADVISED 
          OF THE POSSIBILITY OF SUCH DAMAGES. 
          IF THESE LAWS APPLY TO YOU, SOME OR ALL OF THE ABOVE DISCLAIMERS, EXCLUSIONS OR LIMITATIONS 
          MAY NOT APPLY TO YOU, AND YOU MAY HAVE ADDITIONAL RIGHTS.' => 'Podatki na spletnih straneh so izključno informativne narave in nimajo nobenih 
              pravnih posledic oziroma na njihovi podlagi ne morejo nastati nikakršne obveznosti ali pravice, 
              niti jih ni mogoče uporabiti v postopku uveljavljanja ali dokazovanja morebitnih 
              pravic ali zahtevkov. Uporaba spletnih strani je na lastno odgovornost. 
              Združenje si prizadeva za točnost in ažurnost podatkov, 
              objavljenih na njegovih spletnih straneh. 
              Združenje ne odgovarja za kakršnokoli škodo, ki bi izhajala iz obstoja, dostopa, uporabe in/ali nezmožnosti 
              uporabe spletnih strani in/ali informacij ali bi bila povezana z njimi, 
              niti za kakršnekoli napake ali pomanjkljivosti v njihovi vsebini.
    ',
    'Limitation on Liability' => 'Omejitev odgovornosti',
    'Services' => 'Storitve',
    'Terms' => 'Pogoji',
    'The AirRenty Service is one of the Basic IT Products, provided to you by Basic IT s.p.. (ID 89350847)
          These Terms of Use therefore constitute an agreement between you and Basic IT s.p.. ' => 'AirRenty Storitev je produkt od Basic IT s.p.. (ID 89350847)',
    'The Data Policy' => 'Politika podatkov',
    'These Terms of Use govern your use of web site and provide information about the AirRenty Service, 
          outlined below. When you use AirRenty, you agree to these terms.' => 'Ti pogoji uporabe predstavljajo uporabo spletne strani
            ter podajajo informacije glede AirRenty storitve. Z uporabo spletne strani se strinjate s pogoji uporabe.
    ',
    'We do not collect or process any personal data' => 'Ne pridobivamo ali procesiramo osebnih podatkov',
    'Cancel' => 'Prekliči',
    'Register' => 'Registracija',
    'Save' => 'Shrani',
];
