<?php

/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */

return [
    'Your account has been successfully created.' => 'Vaš račun je ustvarjen.',
    'Welcome to' => 'Pozdravljeni na',
    'Follow the link below to verify your email' => 'Sledite spodni povezavi za verifikacijo',
    'This message was generated by' => 'Sporočilo je bilo zgenerirano na',
    'If you think you received this email by error please contact' => 'Će ste prejeli to sporočilo po pomoti, prosimo kontaktirajte',
    'Reset password' => 'Ponastavitev gesla',
    'Follow the link below to reset your password' => 'Prosimo sledite spodnji povezavi za ponastavitev gesla',
    
];
