<?php
use yii\helpers\Html;
?>
<hr>
<p style="margin: 1em 0;padding: 0;color: #606060;font-family: Helvetica;font-size: 10px;line-height: 100%;text-align: left;">
  This message was generated by <?= Yii::$app->params["site_name"] ?>. 
  If you think you received this email by error please contact <?= Yii::$app->params["adminEmail"] ?>
</p>

